name: CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: build & push backend to docker hub
      uses: docker/build-push-action@v1.1.0
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        repository: ${{ secrets.DOCKER_HUB_REPO }}
        path: ./copa-filmes-backend
        tag_with_ref: true
        
  deploy:
    
    runs-on: ubuntu-latest
    
    steps:
    - name: login no azure
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: deploy para azure web apps
      uses: Azure/webapps-deploy@v2
      with:
        app-name: api-copa-filmes
        images: ${{ secrets.DOCKER_HUB_REPO }}:latest
